// AUTO-GENERATED by scripts/i18n-bundle.ts - run `npm run i18n:bundle`. Do not edit by hand.
import { registerLocale } from "./index.ts";
import de_common from "./locales/de/common.json" with { type: "json" };
import de_core from "./locales/de/core.json" with { type: "json" };
import de_leveling from "./locales/de/leveling.json" with { type: "json" };
import de_moderation from "./locales/de/moderation.json" with { type: "json" };
import de_preferences from "./locales/de/preferences.json" with { type: "json" };
import es_common from "./locales/es/common.json" with { type: "json" };
import es_core from "./locales/es/core.json" with { type: "json" };
import es_leveling from "./locales/es/leveling.json" with { type: "json" };
import es_moderation from "./locales/es/moderation.json" with { type: "json" };
import es_preferences from "./locales/es/preferences.json" with { type: "json" };
import fr_common from "./locales/fr/common.json" with { type: "json" };
import fr_core from "./locales/fr/core.json" with { type: "json" };
import fr_leveling from "./locales/fr/leveling.json" with { type: "json" };
import fr_moderation from "./locales/fr/moderation.json" with { type: "json" };
import fr_preferences from "./locales/fr/preferences.json" with { type: "json" };
import pt_BR_common from "./locales/pt-BR/common.json" with { type: "json" };
import pt_BR_core from "./locales/pt-BR/core.json" with { type: "json" };
import pt_BR_leveling from "./locales/pt-BR/leveling.json" with { type: "json" };
import pt_BR_moderation from "./locales/pt-BR/moderation.json" with { type: "json" };
import pt_BR_preferences from "./locales/pt-BR/preferences.json" with { type: "json" };
import ru_common from "./locales/ru/common.json" with { type: "json" };
import ru_core from "./locales/ru/core.json" with { type: "json" };
import ru_leveling from "./locales/ru/leveling.json" with { type: "json" };
import ru_moderation from "./locales/ru/moderation.json" with { type: "json" };
import ru_preferences from "./locales/ru/preferences.json" with { type: "json" };
import zh_CN_common from "./locales/zh-CN/common.json" with { type: "json" };
import zh_CN_core from "./locales/zh-CN/core.json" with { type: "json" };
import zh_CN_leveling from "./locales/zh-CN/leveling.json" with { type: "json" };
import zh_CN_moderation from "./locales/zh-CN/moderation.json" with { type: "json" };
import zh_CN_preferences from "./locales/zh-CN/preferences.json" with { type: "json" };

/**
 * Register every bundled translation file. Idempotent - safe to call per boot.
 * English is the source of truth (module `i18n` bundles); these layer on top,
 * and any missing key falls back to English automatically.
 */
let registered = false;

export function registerBundledLocales(): void {
	if (registered) return;
	registerLocale("de", "common", de_common);
	registerLocale("de", "core", de_core);
	registerLocale("de", "leveling", de_leveling);
	registerLocale("de", "moderation", de_moderation);
	registerLocale("de", "preferences", de_preferences);
	registerLocale("es", "common", es_common);
	registerLocale("es", "core", es_core);
	registerLocale("es", "leveling", es_leveling);
	registerLocale("es", "moderation", es_moderation);
	registerLocale("es", "preferences", es_preferences);
	registerLocale("fr", "common", fr_common);
	registerLocale("fr", "core", fr_core);
	registerLocale("fr", "leveling", fr_leveling);
	registerLocale("fr", "moderation", fr_moderation);
	registerLocale("fr", "preferences", fr_preferences);
	registerLocale("pt-BR", "common", pt_BR_common);
	registerLocale("pt-BR", "core", pt_BR_core);
	registerLocale("pt-BR", "leveling", pt_BR_leveling);
	registerLocale("pt-BR", "moderation", pt_BR_moderation);
	registerLocale("pt-BR", "preferences", pt_BR_preferences);
	registerLocale("ru", "common", ru_common);
	registerLocale("ru", "core", ru_core);
	registerLocale("ru", "leveling", ru_leveling);
	registerLocale("ru", "moderation", ru_moderation);
	registerLocale("ru", "preferences", ru_preferences);
	registerLocale("zh-CN", "common", zh_CN_common);
	registerLocale("zh-CN", "core", zh_CN_core);
	registerLocale("zh-CN", "leveling", zh_CN_leveling);
	registerLocale("zh-CN", "moderation", zh_CN_moderation);
	registerLocale("zh-CN", "preferences", zh_CN_preferences);
	registered = true;
}
