import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Regenerate `src/i18n/bundled.ts` from the translation files under
 * `src/i18n/locales/<code>/<namespace>.json`. Static imports keep the build
 * bundler-safe (no runtime fs reads); adding a translation file just means
 * running `npm run i18n:bundle`. English lives in module `i18n` bundles, so the
 * `en` folder and files starting with `_` are skipped.
 */

const here = dirname(fileURLToPath(import.meta.url));
const i18nDir = join(here, "..", "i18n");
const localesDir = join(i18nDir, "locales");

const safe = (s: string): string => s.replace(/[^a-zA-Z0-9]/g, "_");

interface Entry {
	locale: string;
	namespace: string;
	importName: string;
	path: string;
}

function collect(): Entry[] {
	const entries: Entry[] = [];
	for (const locale of readdirSync(localesDir, { withFileTypes: true })) {
		if (!locale.isDirectory() || locale.name === "en") continue;
		const dir = join(localesDir, locale.name);
		for (const file of readdirSync(dir)) {
			if (!file.endsWith(".json") || file.startsWith("_")) continue;
			const namespace = file.replace(/\.json$/, "");
			entries.push({
				locale: locale.name,
				namespace,
				importName: `${safe(locale.name)}_${safe(namespace)}`,
				path: `./locales/${locale.name}/${file}`,
			});
		}
	}
	entries.sort((a, b) => a.importName.localeCompare(b.importName));
	return entries;
}

function render(entries: Entry[]): string {
	const imports = entries
		.map((e) => `import ${e.importName} from "${e.path}" with { type: "json" };`)
		.join("\n");
	const registrations = entries
		.map((e) => `\tregisterLocale("${e.locale}", "${e.namespace}", ${e.importName});`)
		.join("\n");
	return `// AUTO-GENERATED by scripts/i18n-bundle.ts - run \`npm run i18n:bundle\`. Do not edit by hand.
import { registerLocale } from "./index.ts";
${imports}

/**
 * Register every bundled translation file. Idempotent - safe to call per boot.
 * English is the source of truth (module \`i18n\` bundles); these layer on top,
 * and any missing key falls back to English automatically.
 */
let registered = false;

export function registerBundledLocales(): void {
\tif (registered) return;
${registrations}
\tregistered = true;
}
`;
}

const entries = collect();
const out = join(i18nDir, "bundled.ts");
writeFileSync(out, render(entries));
if (!existsSync(out)) throw new Error("failed to write bundled.ts");
console.log(`i18n:bundle - wrote ${entries.length} bundle(s) to src/i18n/bundled.ts`);
